### ISSUE TITLE
Non-revocation branches of received HTLC script reported as unsolvable

### ISSUE THREAD

**Issue by ysangkok** [RKlompUU/SCRIPTAnalyser#1]
I tried analysing the [received HTLC output script](https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#received-htlc-outputs). Only the revocation branch is reported solvable. Did I make an error while converting the numbers to OPs and PUSH'es? I don't think that can be it, since I already find the constraints on branch 1 suspicious. Why is the hash asserted to be equal, the else branch should be condition on it NOT being equal?

Thank you for your time, very interesting project!  

```
 % stack exec SCRIPTAnalyser-exe < scripts/lreceivedhtlc
-------------------------
---------- AST ----------
0:	OP_DUP;
1:	OP_HASH160;
2:	BS_20 "4acc5a692dac2d692dac2d692dac2d692dac2d00";
3:	OP_EQUAL;
4:	IF {
5:	OP_CHECKSIG;
6:	} ELSE {
7:	BS_33 "5e4ff47ceb3a51cdf7ddd80afc4acc5a692dac2d692dac2d692dac2d692dac2d00";
8:	OP_SWAP;
9:	OP_SIZE;
10:	BS_1 "20";
11:	OP_EQUAL;
12:	IF {
13:	OP_HASH160;
14:	BS_20 "4acc5a692dac2d692dac2d692dac2d692dac2d00";
15:	OP_EQUALVERIFY;
16:	OP_2;
17:	OP_SWAP;
18:	BS_33 "5e4ff47ceb3a51cdf7ddd80afc4acc5a692dac2d692dac2d692dac2d692dac2d00";
19:	OP_2;
20:	OP_CHECKMULTISIG;
21:	} ELSE {
22:	OP_DROP;
23:	BS_1 "64";
24:	OP_CHECKLOCKTIMEVERIFY;
25:	OP_DROP;
26:	OP_CHECKSIG;
27:	}
28:	}
-------------------------
-------- Inferred -------
---
--- Symbolic evaluation report of execution branch 0
---
Branch's decision points:
	-> Line 4: True
Required initial main stack:
	|------------------|
head -> | X_(0)
	| X_(-1)
	|------------------|
Required initial alternative stack:
head -> |------------------|
Inferred constraints:
	Constraint: Sig (X_(-1)) (X_(0))
	Constraint: (Hash_20 (X_(0))) == (BS_20 "4acc5a692dac2d692dac2d692dac2d692dac2d00")
Resulting symbolic stack:
	[]

---
--- Symbolic evaluation report of execution branch 1
---
!!!!! This branch is unsolvable !!!!!
Branch's decision points:
	-> Line 4: False
	-> Line 12: True
Required initial main stack:
	|------------------|
head -> | X_(0)
	|------------------|
Required initial alternative stack:
head -> |------------------|
Inferred constraints:
	Constraint: (Hash_20 (X_(0))) == (BS_20 "4acc5a692dac2d692dac2d692dac2d692dac2d00")
	Constraint: (Length (X_(0))) == (BS_1 "20")
	Constraint: Not ((Hash_20 (X_(0))) == (BS_20 "4acc5a692dac2d692dac2d692dac2d692dac2d00"))
Resulting symbolic stack:
	[Int 2,
	BS_33 "5e4ff47ceb3a51cdf7ddd80afc4acc5a692dac2d692dac2d692dac2d692dac2d00",
	BS_33 "5e4ff47ceb3a51cdf7ddd80afc4acc5a692dac2d692dac2d692dac2d692dac2d00",
	Int 2]

---
--- Symbolic evaluation report of execution branch 2
---
!!!!! This branch is unsolvable !!!!!
Branch's decision points:
	-> Line 4: False
	-> Line 12: False
Required initial main stack:
	|------------------|
head -> | X_(0)
	| X_(-1)
	| X_(-2)
	|------------------|
Required initial alternative stack:
head -> |------------------|
Inferred constraints:
	Constraint: Sig (X_(-2)) (X_(-1))
	Constraint: ((BS_1 "64") < (blockNum or timestamp)) /\ ((((BS_1 "64") >= (Int 500000000)) /\ ((blockNum or timestamp) >= (Int 500000000))) \/ (((BS_1 "64") < (Int 500000000)) /\ ((blockNum or timestamp) < (Int 500000000))))
	Constraint: Not ((Length (X_(0))) == (BS_1 "20"))
	Constraint: Not ((Hash_20 (X_(0))) == (BS_20 "4acc5a692dac2d692dac2d692dac2d692dac2d00"))
Resulting symbolic stack:
	[]

------------------------
-------- Verdict -------
types correct, 1 branch(es) viable
```

**Comment by RKlompUU** [comment]
Very interesting! Actually, branch 1 is correctly stating it is not solvable. And, branch 2 proves that there is a bug in the analyser.

Let's start with discussing branch 1:
In order to solve following this branch, X_0 must be instantiated such that:
   - The result of hashing it **does not** equal the BS_20 pushed at line 2
   - **And**, the result of hashing it **does** equal the BS_20 pushed at line 14

Should be solvable, right? But, notice that the constants pushed at line 2 and 14 are equal.. Thus, the requirements are semantically equivalent to:
   - The result of hashing it **does not** equal the BS_20 pushed at line 2
   - **And**, the result of hashing it **does** equal _that same bytestring_

There exists no instantiation for X_0 to fulfill both those constraints, thus the tool correctly concludes that branch 1 cannot be correctly executed. Look at what happens when you change either the constant at line 2 or at line 14, the tool will then report that branch 1 is executable.

Branch 2, however, in your script, does actually show that there is a bug in the analysis tool. During generation of prolog statements, the tool created the following prolog expression for linking the logic of (e1 == e2):
`(T17bs #= T6bs #==> T29ints #= 1),`
`(T17bs #\= T6bs #==> T29ints #= 0)` 
That second line states that, if the bytestring length of e1 does not equal the bytestring length of e2, then the resulting computation for any e1 == e2 will always result in false (or **0**). This is a valid conclusion.
However, that first line states the converse, that when the bytestring lengths of e1 and e2 are equal, the resulting computation for any e1 == e2 will always result in true (or **1**). This is not necessarily true, there exist many value pairs e1, e2 of equal bytestring lengths where computing e1 == e2 results in False.
I changed it and am in the process of committing and pushing the fix. The correct prolog statements to link the logic of (e1 == e2) are:
`(T17bs #= T6bs #==> T29ints in (0..1)),`
`(T17bs #\= T6bs #==> T29ints #= 0)`

Thank you for your interest in the project!
